INSERT INTO person (firstname, lastname, address, gender, arrombado) VALUES
('João', 'Silva', 'Rua A, 123', 'male', true),
('Maria', 'Santos', 'Rua B, 456', 'female', false),
('Pedro', 'Oliveira', 'Rua C, 789', 'male', true),
('Ana', 'Ferreira', 'Av. X, 234', 'female', false),
('Rafael', 'Gomes', 'Rua Y, 567', 'male', true),
('Julia', 'Rodrigues', 'Rua Z, 890', 'female', false),
('Gustavo', 'Alves', 'Av. A, 111', 'male', true),
('Camila', 'Martins', 'Rua B, 222', 'female', false),
('Lucas', 'Ribeiro', 'Rua C, 333', 'male', true),
('Mariana', 'Pereira', 'Av. D, 444', 'female', false),
('Felipe', 'Souza', 'Rua E, 555', 'male', true),
('Beatriz', 'Almeida', 'Rua F, 666', 'female', false),
('Arthur', 'Lima', 'Av. G, 777', 'male', true),
('Isabella', 'Siqueira', 'Rua H, 888', 'female', false),
('Henrique', 'Castro', 'Rua I, 999', 'male', true),
('Carla', 'Nunes', 'Av. J, 1010', 'female', false),
('Thiago', 'Costa', 'Rua K, 1111', 'male', true),
('Natália', 'Mendes', 'Rua L, 1212', 'female', false),
('Paulo', 'Araújo', 'Av. M, 1313', 'male', true),
('Larissa', 'Farias', 'Rua N, 1414', 'female', false),
('Renato', 'Barbosa', 'Rua O, 1515', 'male', true),
('Vanessa', 'Rocha', 'Av. P, 1616', 'female', false),
('Cesar', 'Fonseca', 'Rua Q, 1717', 'male', true);

