spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/erudio-curso-db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#      show-sql: true
#spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect




