security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/erudio-curso-db
    username: postgres
    password: root
    pool-size: 30
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#      show-sql: true
#spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect
swagger:
  urlExample: https://github.com/vaulthunteroliveira/rest-with-spring-boot-and-java-erudio
  summary: Finds all people

spring-doc:
  pathToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true




