spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/erudio-curso-db
    username: postgres
    password: root
    pool-size: 30
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#      show-sql: true
#spring.jpa.database-platform = org.hibernate.dialect.PostgreSQL94Dialect




